Syntax highlighted code block

# Header 1**Bold** 'My 1st Blog EVER'
## Header 2
### Header 3

- Bulleted
- List

1. Numbered
2. List

**Bold** and _Italic_ and `Code` text

[Link](url) and ![Image](src)


theme: jekyll-theme-midnight

